In [1]:
from numpy import random
import numpy as np
import pandas as pd
a=random.choice([1,2,3],size=(4,2))
a=np.array(a)
b=(a.ndim)
y=a.shape
print(y)
z=len(a)
print(b)
print(z)

(4, 2)
2
4


In [2]:
first=np.array([100,110,120,130,140,150,160,170,180,190])
lord=first.reshape(5,2)
lord

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [3]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
Newarray=[]
for  i in range (len(sampleArray)):
  Newarray.append(sampleArray[i,2])
Newarray=np.array(Newarray)
Newarray

array([33, 66, 99])

In [4]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24],[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
a=[]
t=0
for i in range (len(sampleArray)):
  for j in range (len(sampleArray[i])):
    if i%2!=0 and j%2==0:
      t=t+1
      a.append(sampleArray[i,j])
a=np.array(a)
t=t//2
a=a.reshape(t,t)
a

array([[15, 21],
       [39, 45]])

In [5]:
from numpy.core.getlimits import array
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
arrayresult=[]
for i in range (len(arrayOne)):
  for j in range (len(arrayOne[i])):
    arrayresult.append(arrayOne[i,j]+arrayTwo[i,j])
arrayresult=np.array(arrayresult)
arrayresult=arrayresult.reshape(2,3)
arrayresult

array([[20, 39, 33],
       [25, 25, 28]])

In [6]:
df=pd.read_csv('/content/USA_cars_datasets.csv')
new=df.dropna()
new.head()

Unnamed: 0  price      brand    model  year   title_status   mileage  \
0           0   6300     toyota  cruiser  2008  clean vehicle  274117.0   
1           1   2899       ford       se  2011  clean vehicle  190552.0   
2           2   5350      dodge      mpv  2018  clean vehicle   39590.0   
3           3  25000       ford     door  2014  clean vehicle   64146.0   
4           4  27700  chevrolet     1500  2018  clean vehicle    6654.0   

    color                  vin        lot       state country      condition  
0   black    jtezu11f88k007763  159348797  new jersey     usa   10 days left  
1  silver    2fmdk3gc4bbb02217  166951262   tennessee     usa    6 days left  
2  silver    3c4pdcgg5jt346413  167655728     georgia     usa    2 days left  
3    blue    1ftfw1et4efc23745  167753855    virginia     usa  22 hours left  
4     red    3gcpcrec2jg473991  167763266     florida     usa  22 hours left

In [7]:
new.tail()

Unnamed: 0  price   brand  model  year   title_status  mileage   color  \
2494        2494   7800  nissan  versa  2019  clean vehicle  23609.0     red   
2495        2495   9200  nissan  versa  2018  clean vehicle  34553.0  silver   
2496        2496   9200  nissan  versa  2018  clean vehicle  31594.0  silver   
2497        2497   9200  nissan  versa  2018  clean vehicle  32557.0   black   
2498        2498   9200  nissan  versa  2018  clean vehicle  31371.0  silver   

                      vin        lot       state country      condition  
2494    3n1cn7ap9kl880319  167722715  california     usa    1 days left  
2495    3n1cn7ap5jl884088  167762225     florida     usa  21 hours left  
2496    3n1cn7ap9jl884191  167762226     florida     usa  21 hours left  
2497    3n1cn7ap3jl883263  167762227     florida     usa    2 days left  
2498    3n1cn7ap4jl884311  167762228     florida     usa  21 hours left

In [8]:
new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2499 entries, 0 to 2498
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Unnamed: 0    2499 non-null   int64  
 1   price         2499 non-null   int64  
 2   brand         2499 non-null   object 
 3   model         2499 non-null   object 
 4   year          2499 non-null   int64  
 5   title_status  2499 non-null   object 
 6   mileage       2499 non-null   float64
 7   color         2499 non-null   object 
 8   vin           2499 non-null   object 
 9   lot           2499 non-null   int64  
 10  state         2499 non-null   object 
 11  country       2499 non-null   object 
 12  condition     2499 non-null   object 
dtypes: float64(1), int64(4), object(8)
memory usage: 273.3+ KB


In [9]:
new['price'].max()

84900

In [10]:
new[new['price']==84900]

Unnamed: 0  price          brand     model  year   title_status  mileage  \
502         502  84900  mercedes-benz  sl-class  2017  clean vehicle  25302.0   

      color                  vin        lot    state country    condition  
502  silver    wddjk7ea3hf044968  167607883  florida     usa  2 days left

In [11]:
new[new['price']==84900]['brand']

502    mercedes-benz
Name: brand, dtype: object

In [18]:
z=df.groupby('brand')
z.get_group('toyota')

Unnamed: 0  price   brand    model  year   title_status   mileage  color  \
0           0   6300  toyota  cruiser  2008  clean vehicle  274117.0  black   

                   vin        lot       state country     condition  
0    jtezu11f88k007763  159348797  new jersey     usa  10 days left

In [24]:
df['brand'].value_counts()

ford               1235
dodge               432
nissan              312
chevrolet           297
gmc                  42
jeep                 30
chrysler             18
bmw                  17
hyundai              15
kia                  13
buick                13
infiniti             12
honda                12
cadillac             10
mercedes-benz        10
heartland             5
land                  4
peterbilt             4
audi                  4
acura                 3
lincoln               2
lexus                 2
mazda                 2
maserati              1
toyota                1
harley-davidson       1
jaguar                1
ram                   1
Name: brand, dtype: int64

In [27]:
z=df.groupby('brand')
z['price'].max()

brand
acura              16900
audi               36400
bmw                61200
buick              37500
cadillac           47500
chevrolet          63200
chrysler           29100
dodge              67000
ford               74000
gmc                48500
harley-davidson    54680
heartland           6680
honda              17200
hyundai             9800
infiniti           18500
jaguar              2800
jeep               21100
kia                21500
land               46900
lexus              55600
lincoln            36300
maserati           30300
mazda              16000
mercedes-benz      84900
nissan             36300
peterbilt           1025
ram                11050
toyota              6300
Name: price, dtype: int64